### ISSUE TITLE
Undefined method old_[attribute]= in Rails 3.2.3

### ISSUE THREAD

**Issue by orangethunder** [mdeering/attribute_normalizer#23]
After upgrading from Rails 3.0, I get the above.  I'm just really looking for confirmation that someone else has got this gem working with Rails 3.2, so I can see if it's something I must fix on my side.
Here's the stack trace:

```
NoMethodError: undefined method `old_account_number=' for #<BankAccount:0x00000006089f48>
from /home/daveungerer/.rvm/gems/ruby-1.9.3-p194/gems/activemodel-3.2.3/lib/active_model/attribute_methods.rb:407:in `method_missing'
from /home/daveungerer/.rvm/gems/ruby-1.9.3-p194/gems/activerecord-3.2.3/lib/active_record/attribute_methods.rb:148:in `method_missing'
from /home/daveungerer/.rvm/gems/ruby-1.9.3-p194/gems/attribute_normalizer-1.0.1/lib/attribute_normalizer/model_inclusions.rb:49:in `rescue in block (2 levels) in normalize_attributes'
from /home/daveungerer/.rvm/gems/ruby-1.9.3-p194/gems/attribute_normalizer-1.0.1/lib/attribute_normalizer/model_inclusions.rb:45:in `block (2 levels) in normalize_attributes'
```

It seems that, at the point the code in model_inclusions.rb is run, the :account_number= method is not yet defined, which causes it to never define :old_account_number=

One other thing: I'm using model inheritance, so if it turns out it that the gem is Rails 3.2 compatible, I'll investigate if that is the actual cause.

**Comment by funglaub** [comment]
Any updates on this?

**Comment by chewi** [comment]
I also get this when using `self.abstract_class = true`.

**Comment by mdeering** [comment]
The code that was causing this issue in the past has been long since removed.  Please open a new issue with the relevant gem versions and information to try and reproduce.
